on:
  - push
  - pull_request

jobs:
  test:
    name: "Test, typecheck and lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
          cache: "npm"

      - name: "Install Dependencies"
        run: npm install

      - name: "Audit"
        run: npm audit

      - name: "Typecheck"
        run: npm run typecheck

      - name: "Lint"
        run: npm run lint

      - name: "Check formatting"
        run: npm run format:check

      - name: "Test"
        run: npm run test --if-present
